Repository jupyter-lsp/jupyterlab-lsp, pull requests merged in 2023-05, with the labels that each got.

#936 Limit the shadow FS initialisation to three attempts
  python_packages/jupyter_lsp/jupyter_lsp/tests/test_virtual_documents_shadow.py
  python_packages/jupyter_lsp/jupyter_lsp/virtual_documents_shadow.py
Labels: bug

#938 Installed bash_language_server not detected / not usable
  atest/01_Editor.robot
  atest/03_Notebook.robot
  atest/examples/Foreign extractors.ipynb
  package.json
  packages/jupyterlab-lsp/schema/plugin.json
  python_packages/jupyter_lsp/jupyter_lsp/specs/bash_language_server.py
  python_packages/jupyter_lsp/jupyter_lsp/specs/config/README.md
  python_packages/jupyter_lsp/jupyter_lsp/specs/config/bash-language-server.schema.json
  requirements/github-actions.yml
  yarn.lock
Labels: maintenance

#940 Add `ignoreSeverities` setting
  packages/jupyterlab-lsp/schema/diagnostics.json
  packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.spec.ts
  packages/jupyterlab-lsp/src/features/diagnostics/diagnostics.ts
Labels: enhancement
