Repository jupyter-lsp/jupyterlab-lsp, pull requests merged in 2024-02, with the labels that each got.

#1044 Fix completions when `type` is not defined
  packages/jupyterlab-lsp/src/features/completion/renderer.ts
  setup.cfg
Labels: bug

#1045 Fix transclusions in JupyterLab 4.0.7+
  packages/jupyterlab-lsp/src/virtual/document.ts
Labels: bug

#1051 Fix settings reconciliation for nested properties
  packages/.eslintrc.js
  packages/jupyterlab-lsp/schema/plugin.json
  packages/jupyterlab-lsp/src/index.ts
  packages/jupyterlab-lsp/src/settings.spec.ts
  packages/jupyterlab-lsp/src/settings.ts
  python_packages/jupyter_lsp/jupyter_lsp/specs/config/README.md
  python_packages/jupyter_lsp/jupyter_lsp/specs/config/pyright.schema.json
Labels: bug

#1050 Update README.md
  README.md
Labels: documentation

#1062 Minor version/debug statement cleanup in preparation for v5.1
  .github/workflows/job.test.yml
  packages/code-jumpers/package.json
  packages/completion-theme/package.json
  packages/jupyterlab-lsp/package.json
  packages/jupyterlab-lsp/src/adapters/fileeditor.ts
  yarn.lock
Labels: maintenance
